services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transfer-system
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    restart: unless-stopped
